### ISSUE TITLE
Does not work with latest braid-design-system

### ISSUE THREAD

**Issue by sirajulmcb** [seek-oss/playroom#169]
When upgrading the examples with braid latest version, playroom is throwing the below error

braid: v28.2.0
playroom: v0.18.1

```
(node:7979) UnhandledPromiseRejectionWarning: Error: Cannot find module 'braid-design-system/lib/themes'
Require stack:
- /Users/sirajul/code/m5nv/ionic-playroom/node_modules/playroom/lib/makeWebpackConfig.js
- /Users/sirajul/code/m5nv/ionic-playroom/node_modules/playroom/lib/start.js
- /Users/sirajul/code/m5nv/ionic-playroom/node_modules/playroom/lib/index.js
- /Users/sirajul/code/m5nv/ionic-playroom/node_modules/playroom/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at relativeResolve (/Users/sirajul/code/m5nv/ionic-playroom/node_modules/playroom/lib/makeWebpackConfig.js:17:13)
    at module.exports (/Users/sirajul/code/m5nv/ionic-playroom/node_modules/playroom/lib/makeWebpackConfig.js:50:13)
    at async module.exports (/Users/sirajul/code/m5nv/ionic-playroom/node_modules/playroom/lib/start.js:7:25)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7979) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7979) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by cheshrkat** [comment]
FWIW I just hit this as well. Reproduced with playroom 0.15.1 and latest/0.21.x; running node v12.16.2.

**Comment by michaeltaranto** [comment]
Hey :wave:

The examples are a point in time demonstration of how to integrate with different libraries, not something we have sought to keep up to date. We wouldnt expect updating to the latest Braid would be doable without making changes to the integration and config of that example.

If there are webpack errors it is likely due to the supplied webpack config not meeting the expectations of the provided components.

If you find a specific case where Playroom is doing the wrong thing please feel free to re-open.
