### ISSUE TITLE
Version 0.27.7 throws when no TS config file is found

### ISSUE THREAD

**Issue by pascalduez** [seek-oss/playroom#247]
Just upgraded playroom from `0.27.2` to `0.27.7` and I now get an exception when starting it.
Note: the project is not using TS.  

Probably introduced in #242 

```
(node:31436) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined                                                                   
    at validateString (internal/validators.js:124:11)                                                    
    at Object.dirname (path.js:1248:5)                                                                   
    at module.exports ([...]/playroom/node_modules/playroom/lib/getStaticTypes.js:27:25)                                                                                           
    at async module.exports ([...]/playroom/node_modules/playroom/lib/makeWebpackConfig.js:19:23)                                                                                  
    at async module.exports ([...]/playroom/node_modules/playroom/lib/start.js:7:25)                                                                                               
(Use `node --trace-warnings ...` to show where the warning was created)           
```

**Comment by caseymhunt** [comment]
I'm experiencing this error message currently, when trying to upgrade my package dependencies.
