### ISSUE TITLE
Bug: toolBar icon fails

### ISSUE THREAD

**Issue by hipstersmoothie** [seek-oss/playroom#39]
When I click the toolbar icon to move the editor to a separate window a blank window pops up and rendering itself goes white too.

The editor console has no errors. But the rendering has a bunch of errors

Here is the stack trace 

```
index.js?dd39:7 Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at eval (webpack-internal:///../../../../playroom/src/Playroom/WindowPortal/index.js:35:20)
    at Array.forEach (<anonymous>)
    at copyStyles (webpack-internal:///../../../../playroom/src/Playroom/WindowPortal/index.js:34:37)
    at WindowPortal.eval [as createWindow] (webpack-internal:///../../../../playroom/src/Playroom/WindowPortal/index.js:70:7)
    at WindowPortal.componentDidMount (webpack-internal:///../../../../playroom/src/Playroom/WindowPortal/index.js:88:12)
    at commitLifeCycles (webpack-internal:///../../../../playroom/node_modules/react-dom/cjs/react-dom.development.js:15255:22)
    at commitAllLifeCycles (webpack-internal:///../../../../playroom/node_modules/react-dom/cjs/react-dom.development.js:16523:7)
    at HTMLUnknownElement.callCallback (webpack-internal:///../../../../playroom/node_modules/react-dom/cjs/react-dom.development.js:149:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///../../../../playroom/node_modules/react-dom/cjs/react-dom.development.js:199:16)
    at invokeGuardedCallback (webpack-internal:///../../../../playroom/node_modules/react-dom/cjs/react-dom.development.js:256:31)
(anonymous) @ index.js?dd39:7
copyStyles @ index.js?dd39:6
(anonymous) @ index.js?dd39:64
componentDidMount @ index.js?dd39:41
commitLifeCycles @ react-dom.development.js?bffb:15255
commitAllLifeCycles @ react-dom.development.js?bffb:16523
callCallback @ react-dom.development.js?bffb:149
invokeGuardedCallbackDev @ react-dom.development.js?bffb:199
invokeGuardedCallback @ react-dom.development.js?bffb:256
commitRoot @ react-dom.development.js?bffb:16677
completeRoot @ react-dom.development.js?bffb:18069
performWorkOnRoot @ react-dom.development.js?bffb:17997
performWork @ react-dom.development.js?bffb:17901
performSyncWork @ react-dom.development.js?bffb:17873
interactiveUpdates$1 @ react-dom.development.js?bffb:18164
interactiveUpdates @ react-dom.development.js?bffb:2217
dispatchInteractiveEvent @ react-dom.development.js?bffb:4916
react-dom.development.js?bffb:15123 The above error occurred in the <WindowPortal> component:
    in WindowPortal (created by Playroom)
    in div (created by Playroom)
    in Playroom

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js?bffb:15123
logError @ react-dom.development.js?bffb:15157
update.callback @ react-dom.development.js?bffb:15902
callCallback @ react-dom.development.js?bffb:11194
commitUpdateEffects @ react-dom.development.js?bffb:11233
commitUpdateQueue @ react-dom.development.js?bffb:11221
commitLifeCycles @ react-dom.development.js?bffb:15290
commitAllLifeCycles @ react-dom.development.js?bffb:16523
callCallback @ react-dom.development.js?bffb:149
invokeGuardedCallbackDev @ react-dom.development.js?bffb:199
invokeGuardedCallback @ react-dom.development.js?bffb:256
commitRoot @ react-dom.development.js?bffb:16677
completeRoot @ react-dom.development.js?bffb:18069
performWorkOnRoot @ react-dom.development.js?bffb:17997
performWork @ react-dom.development.js?bffb:17901
performSyncWork @ react-dom.development.js?bffb:17873
interactiveUpdates$1 @ react-dom.development.js?bffb:18164
interactiveUpdates @ react-dom.development.js?bffb:2217
dispatchInteractiveEvent @ react-dom.development.js?bffb:4916
react-dom.development.js?bffb:210 Uncaught Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.
    at Object.invokeGuardedCallbackDev (react-dom.development.js?bffb:210)
    at invokeGuardedCallback (react-dom.development.js?bffb:256)
    at commitRoot (react-dom.development.js?bffb:16677)
    at completeRoot (react-dom.development.js?bffb:18069)
    at performWorkOnRoot (react-dom.development.js?bffb:17997)
    at performWork (react-dom.development.js?bffb:17901)
    at performSyncWork (react-dom.development.js?bffb:17873)
    at interactiveUpdates$1 (react-dom.development.js?bffb:18164)
    at interactiveUpdates (react-dom.development.js?bffb:2217)
    at dispatchInteractiveEvent (react-dom.development.js?bffb:4916)
invokeGuardedCallbackDev @ react-dom.development.js?bffb:210
invokeGuardedCallback @ react-dom.development.js?bffb:256
commitRoot @ react-dom.development.js?bffb:16677
completeRoot @ react-dom.development.js?bffb:18069
performWorkOnRoot @ react-dom.development.js?bffb:17997
performWork @ react-dom.development.js?bffb:17901
performSyncWork @ react-dom.development.js?bffb:17873
interactiveUpdates$1 @ react-dom.development.js?bffb:18164
interactiveUpdates @ react-dom.development.js?bffb:2217
dispatchInteractiveEvent @ react-dom.development.js?bffb:4916
react-dom.development.js?bffb:520 Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Playroom
warningWithoutStack @ react-dom.development.js?bffb:520
warnAboutUpdateOnUnmounted @ react-dom.development.js?bffb:16263
scheduleWorkToRoot @ react-dom.development.js?bffb:17508
scheduleWork @ react-dom.development.js?bffb:17548
enqueueSetState @ react-dom.development.js?bffb:11695
Component.setState @ react.development.js?a626:373
(anonymous) @ Playroom.js?cbaf:108
(anonymous) @ Playroom.js?cbaf:174
```

There is another error below this one but it looks to just be because this first error happened

**Comment by markdalgleish** [comment]
Have you modified the webpack config to enable source maps?

**Comment by hipstersmoothie** [comment]
I have not

**Comment by hipstersmoothie** [comment]
Here is most of the webpack config 

```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = ({ title, logo, example, output }) => ({
  title,
  outputPath: './dist/playroom',
  components: './playroom.entry.ts',
  widths: [320, 768, 992, 1200],
  exampleCode:
    example ||
    `
      <Wrapper>
        <Sidebar>
          <SidebarLogo src="${logo}" />
          <SidebarSection title='turbotax' isActive src="${logo}" />
          <SidebarSection title='turbo' src="${logo}" />
        </Sidebar>
        <Main>
          <Navigation hasSidebar>
            <NavLogo src="${logo}" />
            <NavItem label='Search' icon='search' />
            <NavItem label='Help' icon='question' />
          </Navigation>

          <Content>
            <Title>I am some Content!</Title>
          
            <p>This is a test screen.</p>
            
            <LineItem color='celebration'>
              <LineItemIcon icon="thumbs-up" />
              <LineItemContent>
                <LineItemLabel>You got some money!</LineItemLabel>
                <LineItemValue>$1,000</LineItemValue>
              </LineItemContent>
            </LineItem>
          </Content>
          
          <Actions>
            <Button>
            <Icon icon='chevron-left' position="left" size="medium"/>
            Back
            </Button>
            <Button color='primary'>
              Continue
            </Button>
          </Actions>

          <LegalFooter>
            <LegalLinks>
              <a>License Agreement</a>
              <a>Privacy</a>
              <a>Security</a>
            </LegalLinks>
            <LegalCopyright />
          </LegalFooter>
        </Main>
      </Wrapper>
    `,
  webpackConfig: () => ({
    // Custom webpack config goes here...
    output: {
      filename: 'bundle.js',
      path: path.resolve(__dirname, `../out/${output}`)
    },
    module: {
      rules: [
        {
          test: /\.(ts|tsx)$/,
          loader: [
            {
              loader: require.resolve('babel-loader'),
              options: {
                rootMode: 'upward'
              }
            }
          ]
        },
        {
          test: /\.css$/,
          exclude: /codemirror/,
          use: ['style-loader', 'css-loader']
        },
        {
          test: /\.(woff(2)?|ttf|eot|svg|otf)(\?v=\d+\.\d+\.\d+)?$/,
          use: ['file-loader']
        }
      ]
    },
    resolve: {
      extensions: ['.ts', '.tsx', '.js', '.json']
    },
    plugins: [
      new HtmlWebpackPlugin({
        template: path.resolve(path.join(__dirname, 'playroom.html'))
      })
    ]
  })
});
```

**Comment by hipstersmoothie** [comment]
I do have the package linked right now though if that makes a difference

**Comment by hipstersmoothie** [comment]
On second glance this is how i am inject styles into the head with html-webpack-plugin. So this is def not a bug in playroom, just how i am interfacing with the index.html.

I guess what i really need is a way to include things in the head of the page. For example here i need to include a company font icon hosted on an internal CDN. I'm gonna close this issue. Can i open one for a way to modifiy head? Something like storybook's preview-head.html
